<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="173" hostname="ubuntu-Inspiron" name="testcases.UploadAndDownload" tests="322" failures="30" timestamp="2022-06-24T09:24:18 IST" time="32807.258" errors="2">
  <testcase name="ScenesSupport" time="104.742" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ScenesSupport -->
  <system-out/>
  <testcase name="NoiseDetectorPopup" time="104.724" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.NoiseDetectorPopup(UploadAndDownload.java:1088)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- NoiseDetectorPopup -->
  <system-out/>
  <testcase name="SwingerShutdown" time="105.202" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="RemoteZWaveVoicePrompts" time="103.562" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RemoteZWaveVoicePrompts -->
  <system-out/>
  <testcase name="AlarmPhotos" time="103.530" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AlarmPhotos -->
  <system-out/>
  <testcase name="ULCCommercialPowerRestoration" time="103.490" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizSensorTestStep" time="103.417" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PowerGRFJam" time="105.454" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="DisarmPhotos" time="104.456" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DisarmPhotos -->
  <system-out/>
  <testcase name="BurglaryAlarmConfirmationTimer_minutes" time="103.706" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmationTimer_minutes -->
  <system-out/>
  <testcase name="OtherZWaveDeviceLimit" time="103.200" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- OtherZWaveDeviceLimit -->
  <system-out/>
  <testcase name="EngineersReset" time="6.053" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- EngineersReset -->
  <system-out/>
  <testcase name="WellnessPage" time="104.151" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.WellnessPage(UploadAndDownload.java:878)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- WellnessPage -->
  <system-out/>
  <testcase name="AutoStay" time="104.712" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="VoicesVolume" time="105.075" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- VoicesVolume -->
  <system-out/>
  <testcase name="RFJamDetection" time="103.466" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LocalZWaveVoicePrompts" time="103.508" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LocalZWaveVoicePrompts -->
  <system-out/>
  <testcase name="StreamLiveVideoCamerastoIQRemote" time="108.684" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AutoExitTimeExtension" time="103.236" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="IQRemoteResetAuthentication" time="105.421" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- IQRemoteResetAuthentication -->
  <system-out/>
  <testcase name="Bluetooth" time="103.925" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AllChimes" time="103.902" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllChimes -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeeps" time="103.576" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorTamperTroubleBeeps -->
  <system-out/>
  <testcase name="SafetySensorSounds" time="104.317" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SafetySensorSounds -->
  <system-out/>
  <testcase name="StreamSolarData" time="104.617" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- StreamSolarData -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeeps" time="103.460" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ExitBeeps" time="103.857" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ExitBeeps -->
  <system-out/>
  <testcase name="LEDIndicator" time="103.072" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="RFJamSensitivityLevel" time="103.395" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RFJamSensitivityLevel -->
  <system-out/>
  <testcase name="PanelTamperTroubleBeep" time="103.261" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamperTroubleBeep -->
  <system-out/>
  <testcase name="WizSecuritySensorsStep" time="104.202" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SevereWeatherSirenWarning" time="103.449" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SevereWeatherSirenWarning -->
  <system-out/>
  <testcase name="AllChimes" time="103.536" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllChimes -->
  <system-out/>
  <testcase name="PanelTamperBeeps" time="106.210" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizDealerStep" time="105.491" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizDealerStep -->
  <system-out/>
  <testcase name="WizBluetoothDevicesStep" time="105.835" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamperTroubleBeep" time="106.340" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamperTroubleBeep -->
  <system-out/>
  <testcase name="PanelSiren" time="103.686" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelSiren -->
  <system-out/>
  <testcase name="Partitions" time="103.427" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Auxiliarypanic" time="104.153" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Auxiliarypanic -->
  <system-out/>
  <testcase name="MastercodeZwaveManagement" time="105.258" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LongExitDelay" time="104.452" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="FireandLifeSafetyDeviceTroubleBeeps" time="104.318" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- FireandLifeSafetyDeviceTroubleBeeps -->
  <system-out/>
  <testcase name="SecondPreferredLanguage" time="103.739" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelCamera" time="104.699" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LocalZWaveVoicePrompts" time="103.718" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LocalZWaveVoicePrompts -->
  <system-out/>
  <testcase name="SecurityPage" time="103.362" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SecurityPage(UploadAndDownload.java:892)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SecurityPage -->
  <system-out/>
  <testcase name="GlobalIntrusionSoundsandSirens" time="105.674" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Policepanic" time="103.593" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SecurityPage" time="104.159" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecurityPage -->
  <system-out/>
  <testcase name="SensorLowBatteryTroubleBeep" time="104.249" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorLowBatteryTroubleBeep -->
  <system-out/>
  <testcase name="IQRemoteResetAuthentication" time="103.810" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BackgroundDownloadforUpdates" time="103.370" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="DownloadMobileAppStep" time="106.064" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DownloadMobileAppStep -->
  <system-out/>
  <testcase name="LockScreen" time="103.765" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BeepsandChimesvolume" time="103.645" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Zwave" time="103.955" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Zwave -->
  <system-out/>
  <testcase name="WizDealerStep" time="104.450" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizDealerStep -->
  <system-out/>
  <testcase name="WizIQRemoteStep" time="103.944" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizIQRemoteStep -->
  <system-out/>
  <testcase name="MastercodeSecurityandArming" time="103.673" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- MastercodeSecurityandArming -->
  <system-out/>
  <testcase name="CheckInCheckOut" time="103.408" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- CheckInCheckOut -->
  <system-out/>
  <testcase name="PanelTamper" time="103.354" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ManageMyHome" time="104.353" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.ManageMyHome(UploadAndDownload.java:731)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ManageMyHome -->
  <system-out/>
  <testcase name="MastercodeSirenAndAlarm" time="104.046" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BurglaryAlarmConfirmationTimer_minutes" time="103.734" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmationTimer_minutes -->
  <system-out/>
  <testcase name="StreamSolarData" time="103.935" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="NightTimeModeSetting" time="102.938" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NightTimeModeSetting -->
  <system-out/>
  <testcase name="LongEntryDelay" time="103.665" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="DownloadMobileAppStep" time="105.558" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DownloadMobileAppStep -->
  <system-out/>
  <testcase name="PanelGlassBreakSensor" time="103.200" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelGlassBreakSensor -->
  <system-out/>
  <testcase name="LowBatteryArming" time="103.848" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LowBatteryArming -->
  <system-out/>
  <testcase name="SensorLowBatteryBeeps" time="103.861" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BurglaryAlarmConfirmationTimer_minutes" time="103.418" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmationTimer_minutes -->
  <system-out/>
  <testcase name="CheckInCheckOut" time="105.505" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- CheckInCheckOut -->
  <system-out/>
  <testcase name="GarageDoorDeviceLimit" time="103.386" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="GlobalChimesandVoices" time="103.864" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- GlobalChimesandVoices -->
  <system-out/>
  <testcase name="Nightmodeend" time="104.265" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodeend -->
  <system-out/>
  <testcase name="ExitDelay" time="105.418" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="KeyfobArming" time="105.306" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Duration" time="103.968" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Duration" time="104.056" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Duration -->
  <system-out/>
  <testcase name="Panelcommunicationtestfrequency" time="103.408" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelCamera" time="104.300" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelCamera -->
  <system-out/>
  <testcase name="PowerGSmokeDetectorSiren" time="103.711" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AutoCommunicationTestStartTime" time="104.430" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AutoCommunicationTestStartTime -->
  <system-out/>
  <testcase name="SafetySensorSounds" time="103.416" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SafetySensorSounds(UploadAndDownload.java:654)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SafetySensorSounds -->
  <system-out/>
  <testcase name="WaterFreezeSiren" time="104.056" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WaterFreezeSiren -->
  <system-out/>
  <testcase name="LowBatteryArming" time="106.323" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizUsersStep" time="105.290" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamperTroubleBeep" time="104.012" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamperTroubleBeep -->
  <system-out/>
  <testcase name="Nightmodestart" time="104.303" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodestart -->
  <system-out/>
  <testcase name="SafetySensorSounds" time="103.752" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SafetySensorSounds -->
  <system-out/>
  <testcase name="Zwave" time="104.007" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.Zwave(UploadAndDownload.java:250)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Zwave -->
  <system-out/>
  <testcase name="PanelGlassBreakSensor" time="105.665" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Auxiliarypanic" time="103.267" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Auxiliarypanic -->
  <system-out/>
  <testcase name="Digit6UserCodes" time="103.557" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="MasterUserAddSensors" time="103.679" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AllChimes" time="103.680" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllChimes -->
  <system-out/>
  <testcase name="SoftwareUpdateCheckInterval" time="104.354" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SoftwareUpdateCheckInterval -->
  <system-out/>
  <testcase name="AllTroubleBeeps" time="103.340" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllTroubleBeeps -->
  <system-out/>
  <testcase name="RFJamSensitivityLevel" time="103.837" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RFJamSensitivityLevel -->
  <system-out/>
  <testcase name="Nightmodeend" time="103.286" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodeend -->
  <system-out/>
  <testcase name="PanelWiFiConnectivityWarningPrompts" time="104.422" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelWiFiConnectivityWarningPrompts -->
  <system-out/>
  <testcase name="WizIQRemoteStep" time="105.540" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizIQRemoteStep -->
  <system-out/>
  <testcase name="WellnessPage" time="106.326" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessPage -->
  <system-out/>
  <testcase name="TroubleBeepsTimeout" time="105.497" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- TroubleBeepsTimeout -->
  <system-out/>
  <testcase name="Partitions" time="104.799" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Partitions -->
  <system-out/>
  <testcase name="SettingPhotos" time="104.961" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="NightTimeModeSetting" time="103.206" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NightTimeModeSetting -->
  <system-out/>
  <testcase name="SIAPowerRestoration" time="104.727" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="InstallerAccessRequiresUserPermission" time="104.097" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="EngineersReset" time="6.054" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- EngineersReset -->
  <system-out/>
  <testcase name="SensorAutoLearnOpenCloseReports" time="103.395" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AllTroubleBeeps" time="103.933" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.AllTroubleBeeps(UploadAndDownload.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AllTroubleBeeps -->
  <system-out/>
  <testcase name="BluetoothDisarm" time="103.645" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LowBatteryArming" time="105.211" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LowBatteryArming -->
  <system-out/>
  <testcase name="NoDelay" time="105.344" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BurglaryAlarmConfirmation" time="103.680" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmation -->
  <system-out/>
  <testcase name="FontSize" time="103.725" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- FontSize -->
  <system-out/>
  <testcase name="SecurityPage" time="103.296" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecurityPage -->
  <system-out/>
  <testcase name="AllTroubleBeeps" time="104.967" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllTroubleBeeps -->
  <system-out/>
  <testcase name="NightTimeModeSetting" time="103.713" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actualvalues are different so failed expected [Enabled] but found [Display Only]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actualvalues are different so failed expected [Enabled] but found [Display Only]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.settingvalidator(Validation.java:21)
at testcases.UploadAndDownload.NightTimeModeSetting(UploadAndDownload.java:682)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- NightTimeModeSetting -->
  <system-out/>
  <testcase name="AllSoundsinPartition1" time="105.457" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelAmbientNoiseDetector_BETA" time="105.263" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.PanelAmbientNoiseDetector_BETA(UploadAndDownload.java:997)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PanelAmbientNoiseDetector_BETA -->
  <system-out/>
  <testcase name="WellnessSupport" time="103.208" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessSupport -->
  <system-out/>
  <testcase name="GlobalChimesandVoices" time="103.641" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SupervisoryEmergency" time="103.404" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BurglaryAlarmConfirmation" time="103.745" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmation -->
  <system-out/>
  <testcase name="SecureArming" time="104.541" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecureArming -->
  <system-out/>
  <testcase name="TroubleBeepsTimeout" time="103.623" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- TroubleBeepsTimeout -->
  <system-out/>
  <testcase name="LocalZWaveVoicePrompts" time="103.765" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.LocalZWaveVoicePrompts(UploadAndDownload.java:430)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LocalZWaveVoicePrompts -->
  <system-out/>
  <testcase name="panelCameraMotionDetector" time="103.539" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AutoBypass" time="104.403" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizIQRemoteStep" time="103.538" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.WizIQRemoteStep(UploadAndDownload.java:836)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- WizIQRemoteStep -->
  <system-out/>
  <testcase name="Nightmodestart" time="104.677" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodestart -->
  <system-out/>
  <testcase name="ScenesSupport" time="103.900" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.ScenesSupport(UploadAndDownload.java:871)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ScenesSupport -->
  <system-out/>
  <testcase name="DisplayType" time="106.009" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="TouchSounds" time="103.674" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="NightTimeModeSetting" time="104.602" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NightTimeModeSetting -->
  <system-out/>
  <testcase name="GlobalIntrusionSoundsandSirens" time="106.230" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- GlobalIntrusionSoundsandSirens -->
  <system-out/>
  <testcase name="FontSize" time="103.385" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Engrade2" time="106.691" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Auxiliarypanic" time="103.605" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.Auxiliarypanic(UploadAndDownload.java:528)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Auxiliarypanic -->
  <system-out/>
  <testcase name="LocalZWaveVoicePrompts" time="104.704" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LocalZWaveVoicePrompts -->
  <system-out/>
  <testcase name="SensorLowBatteryBeeps" time="103.179" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorLowBatteryBeeps -->
  <system-out/>
  <testcase name="AllVoicePrompts" time="104.493" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelWiFiConnectivityWarningPrompts" time="104.043" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelWiFiConnectivityWarningPrompts -->
  <system-out/>
  <testcase name="ScenesSupport" time="103.694" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ScenesSupport -->
  <system-out/>
  <testcase name="SoftwareUpdateCheckInterval" time="104.108" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SoftwareUpdateCheckInterval -->
  <system-out/>
  <testcase name="AlarmVideos" time="104.861" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AlarmVideos -->
  <system-out/>
  <testcase name="SensorVoicePrompts" time="105.030" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorVoicePrompts -->
  <system-out/>
  <testcase name="BurglaryAlarmConfirmation" time="103.779" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.BurglaryAlarmConfirmation(UploadAndDownload.java:1046)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- BurglaryAlarmConfirmation -->
  <system-out/>
  <testcase name="AllowKeyfobAlarmDisarm" time="104.507" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="BurglaryAlarmConfirmationTimer_minutes" time="104.525" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.BurglaryAlarmConfirmationTimer_minutes(UploadAndDownload.java:1053)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- BurglaryAlarmConfirmationTimer_minutes -->
  <system-out/>
  <testcase name="SecureArming" time="104.382" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecureArming -->
  <system-out/>
  <testcase name="BackgroundDownloadforUpdates" time="103.894" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BackgroundDownloadforUpdates -->
  <system-out/>
  <testcase name="MastercodeSecurityandArming" time="104.286" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizSoftwareUpdateStep" time="104.229" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SecurityPage" time="103.217" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecurityPage -->
  <system-out/>
  <testcase name="MastercodeSecurityandArming" time="103.235" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- MastercodeSecurityandArming -->
  <system-out/>
  <testcase name="PanelCamera" time="104.111" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelCamera -->
  <system-out/>
  <testcase name="NoiseDetectorDuration" time="105.496" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Nightmodeend" time="103.539" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodeend -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeep" time="103.210" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorTamperTroubleBeep -->
  <system-out/>
  <testcase name="PanelTamper" time="103.698" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamper -->
  <system-out/>
  <testcase name="NoiseDetectorPopup" time="109.814" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NoiseDetectorPopup -->
  <system-out/>
  <testcase name="WellnessSupport" time="103.352" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.WellnessSupport(UploadAndDownload.java:458)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- WellnessSupport -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeep" time="103.297" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SensorTamperTroubleBeep(UploadAndDownload.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SensorTamperTroubleBeep -->
  <system-out/>
  <testcase name="PanelAmbientNoiseDetector_BETA" time="104.494" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelAmbientNoiseDetector_BETA -->
  <system-out/>
  <testcase name="ZWavePrimaryController" time="103.636" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="NoiseDetectorPopup" time="104.449" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NoiseDetectorPopup -->
  <system-out/>
  <testcase name="RFJamSensitivityLevel" time="103.403" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RFJamSensitivityLevel -->
  <system-out/>
  <testcase name="PanelAmbientNoiseDetector_BETA" time="105.733" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelAmbientNoiseDetector_BETA -->
  <system-out/>
  <testcase name="SwingerShutdown" time="104.437" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SwingerShutdown -->
  <system-out/>
  <testcase name="AllTroubleBeeps" time="105.516" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AllTroubleBeeps -->
  <system-out/>
  <testcase name="SevereWeatherSirenWarning" time="103.771" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SevereWeatherSirenWarning -->
  <system-out/>
  <testcase name="AllChimes" time="104.654" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="RFJamDetectionAlarm" time="103.861" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RFJamDetectionAlarm -->
  <system-out/>
  <testcase name="FireandLifeSafetyDeviceTroubleBeeps" time="103.773" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- FireandLifeSafetyDeviceTroubleBeeps -->
  <system-out/>
  <testcase name="ExitBeeps" time="103.727" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ExitBeeps -->
  <system-out/>
  <testcase name="SensorVoicePrompts" time="104.172" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorVoicePrompts -->
  <system-out/>
  <testcase name="AutoCommunicationTestStartTime" time="103.436" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AutoCommunicationTestStartTime -->
  <system-out/>
  <testcase name="ManageMyHome" time="103.487" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ManageMyHome -->
  <system-out/>
  <testcase name="KeyfobArming" time="107.056" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- KeyfobArming -->
  <system-out/>
  <testcase name="SafetySensorSounds" time="104.700" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SafetySensorSounds -->
  <system-out/>
  <testcase name="SafetySensorChimes" time="109.918" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SwingerShutdown" time="103.267" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SwingerShutdown -->
  <system-out/>
  <testcase name="KeyfobDisarming" time="103.733" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SecureArming" time="103.994" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SecureArming(UploadAndDownload.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SecureArming -->
  <system-out/>
  <testcase name="PanelAmbientNoiseDetector_BETA" time="105.185" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelAmbientNoiseDetector_BETA -->
  <system-out/>
  <testcase name="WizPanelGlassBreakStep" time="109.035" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizPanelGlassBreakStep -->
  <system-out/>
  <testcase name="ManageMyHome" time="103.205" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ManageMyHome -->
  <system-out/>
  <testcase name="SensorLowBatteryTroubleBeep" time="103.540" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SensorLowBatteryTroubleBeep(UploadAndDownload.java:274)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SensorLowBatteryTroubleBeep -->
  <system-out/>
  <testcase name="SwingerShutdownTripCount" time="32.474" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SwingerShutdownTripCount -->
  <system-out/>
  <testcase name="WizSoftwareUpdateStep" time="103.831" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizSoftwareUpdateStep -->
  <system-out/>
  <testcase name="GlobalFireSiren" time="104.375" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SensorLowBatteryBeeps" time="104.317" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorLowBatteryBeeps -->
  <system-out/>
  <testcase name="ThermostatDevice" time="103.250" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ManageMyHome" time="103.543" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ManageMyHome -->
  <system-out/>
  <testcase name="Zwave" time="104.062" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Zwave -->
  <system-out/>
  <testcase name="PowerGLossofSupervisoryforNonEmergencySensors" time="105.929" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="NoiseDetectorPopup" time="105.826" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- NoiseDetectorPopup -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeep" time="103.882" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorTamperTroubleBeep -->
  <system-out/>
  <testcase name="UKFinalExitDoorArming" time="104.231" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SafetySensorChimes" time="14.563" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SafetySensorChimes -->
  <system-out/>
  <testcase name="FireandLifeSafetyDeviceTroubleBeeps" time="103.599" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamperBeeps" time="104.167" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamperBeeps -->
  <system-out/>
  <testcase name="WellnessSupport" time="104.962" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessSupport -->
  <system-out/>
  <testcase name="WellnessSupport" time="103.310" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessSupport -->
  <system-out/>
  <testcase name="RFJamDetectionAlarm" time="105.583" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ScenesSupport" time="104.776" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ScenesSupport -->
  <system-out/>
  <testcase name="Policepanic" time="104.511" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Policepanic -->
  <system-out/>
  <testcase name="WizBluetoothDevicesStep" time="109.722" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizBluetoothDevicesStep -->
  <system-out/>
  <testcase name="MastercodeSirenAndAlarm" time="103.960" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- MastercodeSirenAndAlarm -->
  <system-out/>
  <testcase name="DisplayType" time="103.673" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DisplayType -->
  <system-out/>
  <testcase name="TroubleBeepsTimeout" time="103.271" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- TroubleBeepsTimeout -->
  <system-out/>
  <testcase name="IQRemoteResetAuthentication" time="105.580" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- IQRemoteResetAuthentication -->
  <system-out/>
  <testcase name="MastercodeCameraSettings" time="105.166" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelCamera" time="104.504" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelCamera -->
  <system-out/>
  <testcase name="DownloadMobileAppStep" time="104.981" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizIQRemoteStep" time="104.604" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizIQRemoteStep -->
  <system-out/>
  <testcase name="Language" time="104.023" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="TransitionEffect" time="103.404" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- TransitionEffect -->
  <system-out/>
  <testcase name="SwingerShutdownTripCount" time="32.541" classname="testcases.UploadAndDownload">
    <error type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//select[@name =&#039;ctl00$phBody$drpNewValue&#039;]&quot;}
  (Session info: chrome=102.0.5005.115)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;ubuntu-Inspiron&#039;, ip: &#039;127.0.1.1&#039;, os.name: &#039;Linux&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;5.4.0-117-generic&#039;, java.version: &#039;1.8.0_312&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 102.0.5005.115, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.cccflM}, goog:chromeOptions: {debuggerAddress: localhost:35715}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: dec4b3b8331f574296a0134a4bb0f0d1
*** Element info: {Using=xpath, value=//select[@name =&#039;ctl00$phBody$drpNewValue&#039;]}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@name ='ctl00$phBody$drpNewValue']"}
  (Session info: chrome=102.0.5005.115)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ubuntu-Inspiron', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-117-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 102.0.5005.115, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.cccflM}, goog:chromeOptions: {debuggerAddress: localhost:35715}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: dec4b3b8331f574296a0134a4bb0f0d1
*** Element info: {Using=xpath, value=//select[@name ='ctl00$phBody$drpNewValue']}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at keywords.SettingChangePage.OptionSelector(SettingChangePage.java:42)
at keywords.Settings.swingerShutdownTripCount(Settings.java:1048)
at testcases.UploadAndDownload.SwingerShutdownTripCount(UploadAndDownload.java:666)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- SwingerShutdownTripCount -->
  <system-out/>
  <testcase name="TransitionEffect" time="105.852" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="EUEventSwingerShutdownCount" time="109.234" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Brightness" time="106.441" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelGlassBreakSensorSensitivity" time="104.708" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamper" time="103.639" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamper -->
  <system-out/>
  <testcase name="SupervisoryNonEmerg" time="104.034" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="DisarmPhotos" time="103.687" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.DisarmPhotos(UploadAndDownload.java:346)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DisarmPhotos -->
  <system-out/>
  <testcase name="RemoteZWaveVoicePrompts" time="103.369" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RemoteZWaveVoicePrompts -->
  <system-out/>
  <testcase name="Zwave" time="104.670" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Zwave -->
  <system-out/>
  <testcase name="DisarmPhotos" time="103.416" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DisarmPhotos -->
  <system-out/>
  <testcase name="RemoteZWaveVoicePrompts" time="103.394" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.RemoteZWaveVoicePrompts(UploadAndDownload.java:437)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RemoteZWaveVoicePrompts -->
  <system-out/>
  <testcase name="AlarmVideos" time="103.895" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AlarmPhotos" time="103.414" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamperTroubleBeep" time="103.401" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.PanelTamperTroubleBeep(UploadAndDownload.java:409)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PanelTamperTroubleBeep -->
  <system-out/>
  <testcase name="StreamSolarData" time="104.588" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- StreamSolarData -->
  <system-out/>
  <testcase name="SafetySensorVoicePrompts" time="103.920" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SwingerShutdownTripCount" time="32.618" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SwingerShutdownTripCount -->
  <system-out/>
  <testcase name="OtherZWaveDeviceLimit" time="103.489" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AutoCommunicationTestStartTime" time="104.633" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actualvalues are different so failed expected [null] but found [11:27]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actualvalues are different so failed expected [null] but found [11:27]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.settingvalidator(Validation.java:21)
at testcases.UploadAndDownload.AutoCommunicationTestStartTime(UploadAndDownload.java:1025)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AutoCommunicationTestStartTime -->
  <system-out/>
  <testcase name="SupervisoryNonEmerg" time="105.252" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SupervisoryNonEmerg -->
  <system-out/>
  <testcase name="AmbientNoiseDetectiondBThreshold" time="104.642" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizZWaveDevicesStep" time="105.105" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizDealerStep" time="103.290" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LEDIndicator" time="104.605" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LEDIndicator -->
  <system-out/>
  <testcase name="CheckInCheckOut" time="103.877" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.CheckInCheckOut(UploadAndDownload.java:885)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckInCheckOut -->
  <system-out/>
  <testcase name="SecureArming" time="104.697" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SecureArming -->
  <system-out/>
  <testcase name="WizPanelGlassBreakStep" time="103.359" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Panelcommunicationtestfrequency" time="103.355" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Panelcommunicationtestfrequency -->
  <system-out/>
  <testcase name="WaterFreezeSiren" time="103.741" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SensorLowBatteryTroubleBeep" time="103.406" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorLowBatteryTroubleBeep -->
  <system-out/>
  <testcase name="PanelSiren" time="103.202" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Nightmodestart" time="103.414" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actualvalues are different so failed expected [null] but found [04:24]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actualvalues are different so failed expected [null] but found [04:24]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.settingvalidator(Validation.java:21)
at testcases.UploadAndDownload.Nightmodestart(UploadAndDownload.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Nightmodestart -->
  <system-out/>
  <testcase name="BurglaryAlarmConfirmation" time="104.022" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- BurglaryAlarmConfirmation -->
  <system-out/>
  <testcase name="WellnessPage" time="107.216" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessPage -->
  <system-out/>
  <testcase name="Temperature" time="106.970" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelWiFiConnectivityWarningPrompts" time="103.634" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PanelTamper" time="104.361" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamper -->
  <system-out/>
  <testcase name="PhotoFrameStartTime" time="106.136" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SensorLowBatteryTroubleBeep" time="103.591" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorLowBatteryTroubleBeep -->
  <system-out/>
  <testcase name="WizSoftwareUpdateStep" time="103.095" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizSoftwareUpdateStep -->
  <system-out/>
  <testcase name="TimeFormat" time="104.143" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizSecuritySensorSetupType" time="103.558" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SevereWeatherSirenWarning" time="104.025" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="RFJamSensitivityLevel" time="103.165" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actualvalues are different so failed expected [Normal] but found [On]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actualvalues are different so failed expected [Normal] but found [On]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.settingvalidator(Validation.java:21)
at testcases.UploadAndDownload.RFJamSensitivityLevel(UploadAndDownload.java:493)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RFJamSensitivityLevel -->
  <system-out/>
  <testcase name="CheckInCheckOut" time="106.764" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- CheckInCheckOut -->
  <system-out/>
  <testcase name="VoicesVolume" time="103.742" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SoftwareUpdateCheckInterval" time="104.488" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SoftwareUpdateCheckInterval(UploadAndDownload.java:724)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SoftwareUpdateCheckInterval -->
  <system-out/>
  <testcase name="MasterUserAddSensors" time="104.537" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- MasterUserAddSensors -->
  <system-out/>
  <testcase name="SensorTamperTroubleBeep" time="103.379" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorTamperTroubleBeep -->
  <system-out/>
  <testcase name="Duration" time="103.577" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Duration -->
  <system-out/>
  <testcase name="AutoExitTimeExtension" time="104.165" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AutoExitTimeExtension -->
  <system-out/>
  <testcase name="Auxiliarypanic" time="107.900" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Auxiliarypanic -->
  <system-out/>
  <testcase name="TransitionEffect" time="104.194" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- TransitionEffect -->
  <system-out/>
  <testcase name="UseCommercialSensorandDeviceNames" time="103.307" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SoftwareUpdateCheckInterval" time="103.316" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SoftwareUpdateCheckInterval -->
  <system-out/>
  <testcase name="SensorVoicePrompts" time="103.246" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.SensorVoicePrompts(UploadAndDownload.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SensorVoicePrompts -->
  <system-out/>
  <testcase name="Nightmodestart" time="103.697" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- Nightmodestart -->
  <system-out/>
  <testcase name="SwingerShutdownTripCount" time="32.455" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SwingerShutdownTripCount -->
  <system-out/>
  <testcase name="SirenforWirelessSupervisoryFailures" time="105.053" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WellnessPage" time="104.421" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WellnessPage -->
  <system-out/>
  <testcase name="PowerGLossofSupervisoryforEmergencySensors" time="104.031" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SevereWeatherSirenWarning" time="103.780" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SevereWeatherSirenWarning -->
  <system-out/>
  <testcase name="UseCommercialSensorandDeviceNames" time="104.174" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- UseCommercialSensorandDeviceNames -->
  <system-out/>
  <testcase name="SirenAnnunciation" time="105.200" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SirenAnnunciation -->
  <system-out/>
  <testcase name="AutoCommunicationTestStartTime" time="103.729" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AutoCommunicationTestStartTime -->
  <system-out/>
  <testcase name="ZWavePrimaryController" time="103.126" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ZWavePrimaryController -->
  <system-out/>
  <testcase name="MasterCodeZwave" time="104.152" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AlarmVideos" time="103.539" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AlarmVideos -->
  <system-out/>
  <testcase name="AccountNumber" time="103.747" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="AmbientNoiseDetectiondBThreshold" time="104.029" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- AmbientNoiseDetectiondBThreshold -->
  <system-out/>
  <testcase name="DialerDelay" time="103.453" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ULCCommercialPowerRestoration" time="103.681" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- ULCCommercialPowerRestoration -->
  <system-out/>
  <testcase name="PanelTamperBeeps" time="103.448" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- PanelTamperBeeps -->
  <system-out/>
  <testcase name="PanelVoicePrompts" time="104.144" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="WizPanelGlassBreakStep" time="103.704" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- WizPanelGlassBreakStep -->
  <system-out/>
  <testcase name="GlobalAuxiliarySirens" time="104.159" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Nightmodeend" time="103.355" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected and actualvalues are different so failed expected [null] but found [04:04]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected and actualvalues are different so failed expected [null] but found [04:04]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.settingvalidator(Validation.java:21)
at testcases.UploadAndDownload.Nightmodeend(UploadAndDownload.java:236)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Nightmodeend -->
  <system-out/>
  <testcase name="TroubleBeepsTimeout" time="103.687" classname="testcases.UploadAndDownload">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at keywords.Validation.sameSetting(Validation.java:26)
at testcases.UploadAndDownload.TroubleBeepsTimeout(UploadAndDownload.java:289)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TroubleBeepsTimeout -->
  <system-out/>
  <testcase name="SirenTimeout" time="103.303" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="PowerManagement" time="103.341" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LogLevel" time="103.644" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="MediaVolume" time="105.139" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="RemoteZWaveVoicePrompts" time="103.658" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- RemoteZWaveVoicePrompts -->
  <system-out/>
  <testcase name="SensorVoicePrompts" time="103.770" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SensorVoicePrompts -->
  <system-out/>
  <testcase name="BluetoothDisarmTimeout" time="103.888" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="EngineersReset" time="6.049" classname="testcases.UploadAndDownload">
    <error type="org.openqa.selenium.InvalidSelectorException" message="invalid selector: Unable to locate an element with the xpath expression //span[text()=&#039;Engineer&#039;s Reset&#039;]/parent::span/parent::td/following-sibling::td[1] because of the following error:
SyntaxError: Failed to execute &#039;evaluate&#039; on &#039;Document&#039;: The string &#039;//span[text()=&#039;Engineer&#039;s Reset&#039;]/parent::span/parent::td/following-sibling::td[1]&#039; is not a valid XPath expression.
  (Session info: chrome=102.0.5005.115)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;ubuntu-Inspiron&#039;, ip: &#039;127.0.1.1&#039;, os.name: &#039;Linux&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;5.4.0-117-generic&#039;, java.version: &#039;1.8.0_312&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 102.0.5005.115, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.JTVnwp}, goog:chromeOptions: {debuggerAddress: localhost:44369}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: dd629a0e2959b11064e7ce1420379b34
*** Element info: {Using=xpath, value=//span[text()=&#039;Engineer&#039;s Reset&#039;]/parent::span/parent::td/following-sibling::td[1]}">
      <![CDATA[org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //span[text()='Engineer's Reset']/parent::span/parent::td/following-sibling::td[1] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//span[text()='Engineer's Reset']/parent::span/parent::td/following-sibling::td[1]' is not a valid XPath expression.
  (Session info: chrome=102.0.5005.115)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ubuntu-Inspiron', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-117-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 102.0.5005.115, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.JTVnwp}, goog:chromeOptions: {debuggerAddress: localhost:44369}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: dd629a0e2959b11064e7ce1420379b34
*** Element info: {Using=xpath, value=//span[text()='Engineer's Reset']/parent::span/parent::td/following-sibling::td[1]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at keywords.SettingChangePopup.clickSetting(SettingChangePopup.java:14)
at keywords.Settings.engineersReset(Settings.java:1630)
at testcases.UploadAndDownload.EngineersReset(UploadAndDownload.java:1030)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- EngineersReset -->
  <system-out/>
  <testcase name="EntryDelay" time="103.309" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SIALimits" time="104.626" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="SirenAnnunciation" time="103.591" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LowBatteryArming" time="103.175" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- LowBatteryArming -->
  <system-out/>
  <testcase name="DisarmPhotos" time="103.683" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- DisarmPhotos -->
  <system-out/>
  <testcase name="Firepanic" time="104.187" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="EngineersReset" time="6.053" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- EngineersReset -->
  <system-out/>
  <testcase name="SupervisoryNonEmerg" time="104.779" classname="testcases.UploadAndDownload">
    <skipped/>
  </testcase> <!-- SupervisoryNonEmerg -->
  <system-out/>
  <testcase name="PanelChimes" time="105.245" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="Shuffle" time="104.050" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="ExitBeeps" time="103.798" classname="testcases.UploadAndDownload"/>
  <system-out/>
  <testcase name="LockDevices" time="103.232" classname="testcases.UploadAndDownload"/>
  <system-out/>
</testsuite> <!-- testcases.UploadAndDownload -->
